@startuml
!pragma layout smetana

actor Client
participant "Load Balancer/ESC" as ESC
participant RemoveBookFromCatalogActivity
participant CatalogDao
database "DynamoDB" as DB

Client -> ESC : HTTP request
ESC -> RemoveBookFromCatalogActivity : execute(RemoveBookFromCatalogRequest)
RemoveBookFromCatalogActivity -> CatalogDao : removeBookFromCatalog(bookId)
CatalogDao -> DB : update isActive variable to false using bookId

alt if bookId does not exist
CatalogDao -> RemoveBookFromCatalogActivity : throw BookNotFoundException
RemoveBookFromCatalogActivity -> ESC : transform to KindlePublishingClientException
ESC -> Client : 400 response
else otherwise, continue
end

alt if CatalogItemVersion is already marked as inactive
CatalogDao -> RemoveBookFromCatalogActivity : throw BookInactiveException
RemoveBookFromCatalogActivity -> ESC : transform to KindlePublishingClientException
ESC -> Client : 400 response
else otherwise, continue
end

DB -> CatalogDao : return soft deleted book
CatalogDao -> RemoveBookFromCatalogActivity : return CatalogItemVersion
RemoveBookFromCatalogActivity -> RemoveBookFromCatalogActivity : create and populate RemoveBookFromCatalogResponse
RemoveBookFromCatalogActivity -> ESC : return RemoveBookFromCatalogResponse
ESC -> Client : 200 response

@enduml