@startuml
!pragma layout smetana

actor Client
participant "Load Balancer/ESC" as ESC
participant "RemoveBookFromCatalogActivity" as Activity
participant "CatalogDao" as DAO
database "DynamoDB" as DB

Client -> ESC : HTTP request
ESC -> Activity : execute(RemoveBookFromCatalogRequest)
Activity -> DAO : removeBookFromCatalog(bookId)
DAO -> DB : update isActive variable to false using bookId

alt if bookId does not exist, or it's already marked as false for isActive
DAO -> Activity : throw BookNotFoundException
Activity -> ESC : transform to KindlePublishingClientException
ESC -> Client : 400 response
else otherwise, continue
end

DB -> DAO : ???
DAO -> Activity : ???
Activity -> ESC : return RemoveBookFromCatalogResponse
ESC -> Client : 200 response (with data???)

@enduml