@startuml
!pragma layout smetana

class GetBookActivity {
    - recommendationServiceClient : RecommendationServiceClient
    - catalogDao : CatalogDao

    + execute(request : GetBookRequest) : GetBookResponse
}

class CatalogDao {
    - dynamoDbMapper : DynamoDBMapper

    + getBookFromCatalog(bookId : String) : CatalogItemVersion
    - getLatestVersionOfBook(bookId : String) : CatalogItemVersion
}

class CatalogItemVersion {
    @DynamoDBHashKey bookId : String
    @DynamoDBRangeKey version : int
    - inactive : boolean
    - title : String
    - author : String
    - text : String
    - genre : BookGenre
}

class RecommendationsServiceClient {
    - recommendationsServiceClient : RecommendationsServiceClient

    + getBookRecommendations(genre BookGenre) : List<BookRecommendation>
}

class GetPublishingStatusActivityClass {
    + execute(getPublishingStatusRequest : GetPublishingStatusRequest) : GetPublishingStatusResponse
}

class RemoveBookFromCatalogActivity {
    + execute(removeBookFromCatalogRequest : RemoveBookFromCatalogRequest) : RemoveBookFromCatalogResponse
}

class SubmitBookForPublishingActivity {
    - publishingStatusDao : PublishingStatusDao

    + execute(request : SubmitBookForPublishingRequest) : SubmitBookForPublishingResponse
}

class PublishingStatusDao {
    - dynamoDbMapper : DynamoDBMapper

    + setPublishingStatus(publishingRecordId : String, publishingRecordStatus : PublishingRecordStatus, bookId : String) : PublishingStatusItem
}

class PublishingStatusItem {
    @DynamoDBHashKey publishingRecordId : String
    @DynamoDBRangeKey status : PublishingRecordStatus
    - statusMessage : String
    - bookId : String
}

note right of PublishingStatusItem::publishingRecordId
  Partition Key
end note

note right of PublishingStatusItem::status
  Partition Key
end note

class BookNotFoundException {
    + BookNotFoundException(message : String)
    + BookNotFoundException(message : String, cause : Throwable)
}

class PublishingStatusNotFoundException {
    + PublishingStatusNotFoundException(message : String)
    + PublishingStatusNotFoundException(message : String), cause : Throwable)
}

GetBookActivity --> CatalogDao
GetBookActivity --> RecommendationsServiceClient

SubmitBookForPublishingActivity --> PublishingStatusDao

CatalogDao --> CatalogItemVersion
CatalogDao -> BookNotFoundException

PublishingStatusDao --> PublishingStatusItem

@enduml